# Generated by Django 5.0.6 on 2024-06-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('percentage_ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.house')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_ownership', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.car')),
                ('parking_spot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.parkingspot')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='parking_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.parkingspot'),
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_data', models.CharField(max_length=100)),
                ('apartments', models.ManyToManyField(through='models.Ownership', to='models.apartment')),
                ('cars', models.ManyToManyField(related_name='owners', through='models.CarOwnership', to='models.car')),
                ('reserved_parking_spots', models.ManyToManyField(related_name='residents', to='models.parkingspot')),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.resident'),
        ),
        migrations.AddField(
            model_name='carownership',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.resident'),
        ),
    ]
